### ISSUE TITLE
Outdated @aws-cdk/aws-appsync-alpha dependency in package.json

### ISSUE THREAD

**Issue by hfahlbusch** [sam-goodwin/functionless#107]
functionless version 0.6:

Using the latest "@aws-cdk/aws-appsync-alpha": "2.21.1-alpha.0" package in project gives:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: functionless@0.6.0
npm ERR! Found: @aws-cdk/aws-appsync-alpha@2.21.1-alpha.0
npm ERR! node_modules/@aws-cdk/aws-appsync-alpha
npm ERR!   @aws-cdk/aws-appsync-alpha@"^2.21.1-alpha.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @aws-cdk/aws-appsync-alpha@"^2.17.0-alpha.0" from functionless@0.6.0
npm ERR! node_modules/functionless
npm ERR!   dev functionless@"^0.6.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @aws-cdk/aws-appsync-alpha@2.17.0-alpha.0
npm ERR! node_modules/@aws-cdk/aws-appsync-alpha
npm ERR!   peer @aws-cdk/aws-appsync-alpha@"^2.17.0-alpha.0" from functionless@0.6.0
npm ERR!   node_modules/functionless
npm ERR!     dev functionless@"^0.6.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

It seems that dev or peerDependecies is creation this error.
Would be great if it can be upgraded or more flexible.

**Comment by thantos** [comment]
After some research, it appears CDK's experimental versions do not support semver ranges as the CDK team seems to recognize https://github.com/aws/aws-cdk/issues/15581#issuecomment-896938220.

@sam-goodwin thoughts?

![image](https://user-images.githubusercontent.com/289213/165138950-e125991f-2650-4686-8787-18ca73b8fc6d.png)

**Comment by thantos** [comment]
One option is to use Projen to generate a hand managed list of versions and form at the semver range.

```
^2.17.0-alpha.0 || ^2.18.0-alpha || ^2.19.0-alpha || ^2.20.0-alpha || ^2.21.0-alpha || ^2.21.1-alpha
```

Another caveat is that semver doesn't even support patch ranges so we'd need to push for each version of CDK until app sync is no longer experimental.

**Comment by thantos** [comment]
Another option is to just use `*` for experimental packages, assuming that users will match the version to the rest of CDK 2.0

**Comment by thantos** [comment]
`*` didnt't work, projen resolves `*` to `0.0.0` and forces us to pick a version.

**Comment by sam-goodwin** [comment]
What's the difference between the alpha lib and this one https://www.npmjs.com/package/@aws-cdk/aws-appsync

**Comment by thantos** [comment]
Its only for `CDK 1`

**Comment by thantos** [comment]
```
Argument of type 'Stack' is not assignable to parameter of type 'Construct'.
  Type 'Stack' is missing the following properties from type 'Construct': onValidate, onPrepare, onSynthesizets(2345)
```

**Comment by sam-goodwin** [comment]
Ah ok. Do we need to do a quick fix here by publishing a new version with upgrades dependencies?

**Comment by thantos** [comment]
We'd need to bump the only valid CDK version to the latest on each CDK release, which I don't think is feasible and also a breaking change for all consumers of lower versions. 

For the record, `yarn` just warns at this issue, not fails.

`npm --force` may be required for consumers like @hfahlbusch using `npm` 7+.

I was going to cut a ticket to CDK asking for guidance as well as their versioning is the cause of this issue which would otherwise force us to avoid experimental contracts, duplicate them, or use CDK 1.0 for libraries...

**Comment by thantos** [comment]
Or cut a issue/PR to projen to allow `*` for peerDeps (which is valid npm/yarn, I think).

**Comment by sam-goodwin** [comment]
According to https://projen.io/node.html

You can specify versions like `projen@*`

**Comment by sam-goodwin** [comment]
> Any dependencies without specific version ranges set (such as react or react@*) will given a version range in package.json so that future package upgrades and changes to the generated lockfiles such as package-lock.json or yarn.lock will follow semver.

Do we need to edit package.json manually and use the defaults?

**Comment by thantos** [comment]
Confirmed that `*` in peerDeps would work

Functionless:

```ts
  "peerDependencies": {
    "@aws-cdk/aws-appsync-alpha": "*",
  },
```

With any `appsync-alpha`, no wrning:

```
warning " > functionless@0.0.0" has incorrect peer dependency "aws-cdk-lib@^2.17.0".
```

Without appsync-alpha at all:

```
warning " > functionless@0.0.0" has unmet peer dependency "@aws-cdk/aws-appsync-alpha@*".
warning " > functionless@0.0.0" has incorrect peer dependency "aws-cdk-lib@^2.17.0".
```

**Comment by thantos** [comment]
Ahh, I was under the impression that package.json was readonly and was overwritten. 

Also looks like projen will support this use case soon. https://github.com/projen/projen/issues/1802
