### ISSUE TITLE
Appsync: Support in-line access of properties on the result of a service call

### ISSUE THREAD

**Issue by sam-goodwin** [sam-goodwin/functionless#14]
Support the following access pattern:

```ts
return table.get(..).property
```

Currently, this mistakenly renders a Velocity Template where the RequestMappingTemplate ends with:
```
$util.toJson($request).property
```

It should actually translate to an expression the ResponseMappingTemplate:
```
#set($context.stash.return__val = $context.result.property)
```

**Comment by sam-goodwin** [comment]
@thantos I think https://github.com/functionless/functionless/pull/280 solved this one? Can we close?

**Comment by thantos** [comment]
Yep!
