### ISSUE TITLE
Add utility to pipe all events to an EventBus

### ISSUE THREAD

**Issue by brendo-m** [sam-goodwin/functionless#141]
Right now if you want to pipe all events on an `EventBus` you do `bus.when(stack, "rule", () => true).pipe(...);`. It would be nice to be able to do `bus.whenAny().pipe(...);` or `bus.all().pipe(...)` instead

**Comment by sam-goodwin** [comment]
Duplicate https://github.com/sam-goodwin/functionless/issues/89
