### ISSUE TITLE
AWS Event Bridge

### ISSUE THREAD

**Issue by thantos** [sam-goodwin/functionless#37]
- [x] Operate on a type safe event
- [ ] Define rule
    - [x] Using predicate on the event
    - [ ] Using conditionals inline with targets
    - [ ] Using an existing CDK rule
- [x] Define function to transform event to target service
   - [ ] Using conditionals for rules and many targets
   - [x] Using standalone targets for a single rule
   - [ ] Integrations 
      - [x] Event Bridge
      - [ ] AppSync - https://aws.amazon.com/blogs/mobile/appsync-eventbridge/
      - [ ] ApiGateway #23 
      - [ ] Step Functions #7 
      - [x] Function 
      - [ ] Dynamo 
- [ ] Event bus as service target to publish events
   - [ ] From Step Functions #7
   - [ ] From AppSync - https://github.com/awsed/AppSync2EventBridge/blob/master/index.ts
   - [ ] From API Gateway #23 

### Option 1: As Rule and Target

construct that accepts a bus and a predicate, returns a rule.

```ts
interface MyEventDetail {
    value: string 
}
type MyEvent = EventBusEvent<MyEventDetail, "my-event-detail-type">;

const rule = new EventBridgeRule<MyEvent>(bus, (event): boolean => {
   return event.source == 'lambda' && event.detail.value.startsWith('something');
})
const function = new Function(...);
const target = new EventBridgeTarget<MyEvent>(rule, (event) => {
    function(event.detail)
});
```

### Option 2: As Single Integration

```ts
interface MyEventDetail {
    value: string 
}
type MyEvent = EventBusEvent<MyEventDetail, "my-event-detail-type">;

const function = new Function(...);
new EventBus<MyEvent>(bus, (event, $util) => {
    if($util.matchType<MyEvent>()) {
          function(event.detail);
    }
})
```

### As AppSync target

```ts
import {aws_events} from 'aws-cdl-lib';
import { EventBus } from 'functionless';

cosnt eventBus = new EventBus(new aws_events.EventBus());

const postEvent = new AppsyncResolver<{ id: string }, Item | null>(($context) => {
    eventBus.putEvent($context.arguments);
})
```

**Comment by sam-goodwin** [comment]
What syntax is supported by event bridge's rules engine?

**Comment by thantos** [comment]
They wrote their own... always need to be special

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-events-rule-inputtransformer.html

```
{
  "InputPathsMap" : {Key : Value}, // value to json path
  "InputTemplate" : String //string template
}
```

```
{
   "InputPathsMap": {"instance": "$.detail.instance","status": "$.detail.status"},
   "InputTemplate": '{"myInstance": <instance>,"myStatus": "<instance> is in state \"<status>\""}'
}
```

Only as expressive as string formatting and json path. In the past I've put a lambda in between to be more expressive.

**Comment by thantos** [comment]
Transformations we can support (incomplete)

* Constants
* Object generation
* field/list access
* string formatting

**Comment by thantos** [comment]
Options for supporting multiple targets in the single event bus construct.

Problem, code with conditionals represents imperative code, executed in sequence, however, the targets of a rule in EB are executed in parallel with no relation to each other.

### Option 1 - All/And utility

```ts
new EventBus<MyEvent>(bus, (event, $util) => {
    if($util.matchType<MyEvent>()) {
          $util.and(function(event.detail), function2(event.detail));
    }
})
```

### Option 2 - Show in Sequence, actually in parallel

```ts
new EventBus<MyEvent>(bus, (event, $util) => {
    if($util.matchType<MyEvent>()) {
          // does not actually execute in this order
          function(event.detail);
          const result = function2(event.detail); // fail because events do not support results
    }
})
```

**Comment by sam-goodwin** [comment]
Is the whole event always passed or can filtering be applied to the data passed to the integration?

**Comment by thantos** [comment]
The data can be transformed into a string or object. Any of the event envelope can be used in the rule or the input to the integration.

**Comment by sam-goodwin** [comment]
God damn aws with the inconsistencies!

**Comment by sam-goodwin** [comment]
I lean towards just representing them in sequence and disallowing using the return value. It's simple to read and there's nothing stopping you doing that with the util.and either.

**Comment by thantos** [comment]
## Condition to Rule Design

https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns.html
https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-patterns-content-based-filtering.html

```ts
if(event.detailType == 'MyEvent') {
   ...
}
```

```json
{
   "detail-type": ["MyEvent"]  
}
```

---
```ts
if(event.detailType != 'MyEvent') {
   ...
}
```

```json
{
   "detail-type": [{ "anything-but": "MyEvent" }]  
}
```

---

```ts
if(event.detailType.startsWith('MyEvent')) {
   ...
}
```

```json
{
    "detail-type": [{ "prefix": "MyEvent" }]
}
```
---

```ts
if(event.source === null) { 
   ...
}
```

```json
{
   "source": [null]
}
```

---

```ts
if("name" in event.detail) {
   ... 
}
```

```json
{
    "name": [ { "exists": true } ]
}
```
---

```ts
if(! ("name" in event.detail)) {
   ... 
}
```

or

```ts
if(event.detail.name === undefined) {
   ... 
}
```

```json
{
    "name": [ { "exists": false } ]
}
```
---

```ts
if(event.detail.name === "sam" || event.detail.name === "ryan") {
   ...
}
```

```json
{
    "name": ["sam", "ryan"]
}
```
---
```ts
if(event.detail.name === "sam" && event.detail.lastName === "goodie") {
   ...
}
```

```json
{
   "name": ["sam"],
   "lastName": ["goodie"]
}
```
---
```ts
if(event.detail.names.includes("sam")) {
   ...
}
```

```json
{
   "name": ["sam"]
}
```
---
```ts
if(event.detail.age === 30) {
   ...
}
```

```json
{
   "age": [30]
}
```
---
```ts
if(event.detail.age < 30 && event.detail.age >= 20) {
   ...
}
```

```json
{
   "age": [{ "numeric": [ ">=", 20, "<", 30 ] }]
}
```
---
```ts
if(event.detail.name === "sam" || event.detail.lastName === "goodie") {
   ...
}
```

FAIL - Functionless doesn't support OR logic between two fields as it may result in calling the same function twice. Multiple if statements can be used.

---
```ts
if((event.detail.name === "sam" || event.detail.lastName === "goodie") && event.detailType === "MyEvent") {
   ...
}
```

FAIL - Functionless doesn't support OR logic between two fields as it may result in calling the same function twice. Multiple if statements can be used.

Instead do... if this is the desired behavior

```ts
if(event.detail.lastName === "goodie" && event.detailType === "MyEvent") {
   ...
}

if(event.detail.name === "sam" && event.detailType === "MyEvent") {
   ...
}
```

---

```ts
if(...) else {}
if(...) else if {}
```

FAIL - Functionless doesn't support `else` if `else if` because they imply a perfectly negated event and all rules are evaluated for every event.

---

```ts
if(event.detail.name !== "sam" || event.detail.name !== "ryan") {
   ...
}
if(event.detail.name !== "sam" && event.detail.name !== "ryan") {
   ...
}
```

There is no short circuiting, so `and` and `or` are the same for negation. 

```json
{
    "name": [{ "anything-but": ["sam", "ryan"] }]
}
```

---

```ts
if(event.detail.name === "sam" && event.detail.name === "ryan") {
   ...
}
```

FAIL - Impossible

---

```ts
if(event.detail.name !== "sam" && event.detail.name === "ryan") {
   ...
}
```

We an simplify because its possible to both fail the match and the negation.

```json
{
   "name": ["ryan"] 
}
```

```

**Comment by sam-goodwin** [comment]
Is an `if` the right syntax here? Are rules evaluated in order and the first one that matches is chosen? Or are all rules evaluated in parallel and independently of each other?

**Comment by sam-goodwin** [comment]
Should we instead filter?

```
eventBus.rule(event => event.name === "sam", event => function1(event.field))
```

**Comment by thantos** [comment]
I was thinking it would be nice to create a single function with all of the rules as if statements, but we would need to fail on `else` or `else-if`, there is no order or short circuiting and the transformed values cannot be used in the conditions... so that argues to start with the predicate/target syntax.

**Comment by thantos** [comment]
Can also find a way to display them together later.

**Comment by sam-goodwin** [comment]
> I was thinking it would be nice to create a single function with all of the rules as if statements, but we would need to fail on `else` or `else-if`, there is no order or short circuiting and the transformed values cannot be used in the conditions... so that argues to start with the predicate/target syntax. 

Based on that, I think representing rules as `if` and `else-if` would be the wrong choice then. Things like type narrowing of `if` will not properly represent what's happening in the event bus service. We should avoid using syntax where there is a mismatch between how that syntax would behave in typescript and how the service behaves. Limiting available syntax is ok, but changing its meaning is not.

**Comment by thantos** [comment]
We do want the Narrowing, but we can do that with a predicate.

```ts
eb.rule((event): event is MyEvent => event.detailType === "MyType").to((event) => ...) 
```

the to function parameter should be `MyEvent`.

**Comment by sam-goodwin** [comment]
Oh right, we do want narrowing like that. What I meant was we don't want the narrowing prior to an else-if because there is no sequentially evaluated set of rules.

**Comment by sam-goodwin** [comment]
It's a shame we need to annotate the function like that to narrow it. Wish ts inferred it

**Comment by thantos** [comment]
*Scenario*: a condition can have conflicting statements.
*Examples*:
1
```ts
b === "x" && b !== "x"
```

2
```ts
(b === "x" || b === "y") && b !== "x"
```

3
```ts
(b.startsWith("x") || b === "y") && b !== "x"
```

4
```ts
b === "x" || b !== "x"
```
*Proposal*: EventBridge does not support consistent intra-field AND (`&&`) logic, while we could determine overlapping logic (`b === "x" && b !== "y"` when `b` is "x", it will never be "y"), this logic will be more difficult to prove for prefix, negative prefix, and numeric ranges. Because of this, we will FAIL when `&&` is used in most cases. 

See the table here: https://github.com/sam-goodwin/functionless/issues/37#issuecomment-1066313146 for more.

In the future, this algorithm can be expanded to not fail.

**Comment by sam-goodwin** [comment]
If we did nothing, would it fail at deploy time or runtime? This looks like a user error?

**Comment by thantos** [comment]
*Scenario*: Cross Field logic.
*Examples*:

```ts
b === "x" || c === "y"
```

```ts
b === "x" && c === "y"
```

*Proposal*: 
* AND (`&&`) merge each field within the event patterns, following the rules in the `&&` table here: https://github.com/sam-goodwin/functionless/issues/37#issuecomment-1066313146.
* OR (`||`) will fail when the left and right have more than one key and the keys are different, but will follow the `||` table here: https://github.com/sam-goodwin/functionless/issues/37#issuecomment-1066313146

*Note*: Its clear our ability to reflect logic is limited, but it matches what Event Matchers can do, and multiple rules can be used to make deeper logic. The algorithm can be expanded over time.

**Comment by thantos** [comment]
> If we did nothing, would it fail at deploy time or runtime? This looks like a user error?

EB cannot represent `&&` logic within a field. The only case that `&&` could be represented is when one side of the `&&` will completely clobber the other side.

```ts
b === "x" && b !== "y"
```

Where where the right side will never have an impact because the left will already be false when the right is false. But at this point, why not just write `b === "x"`

The argument against handling this is that the cases can get more complicated. 

```ts
b === 6 && b > 4 && b < 7
```

```ts
b === "hello" && b.startsWith("hel")
```

```ts
b.startsWith("s") && b.startsWith("sta")
```

and because its easy to find invalid cases that are illogical or EB cannot do

```ts
b === "hello" && b === "there" // always false
```

```ts
b > 4 && b < 10 && b > 12
```

**Comment by thantos** [comment]
One exception I've found to the rule here: https://github.com/sam-goodwin/functionless/issues/37#issuecomment-1067147717 is that number range will need to be computed and reduced.

```ts
x > 5 && x < 10
```

```json
{
   x: [{ number: [">", 5, "<", 10] }]
}
```
---

```ts
x > 5 && x < 10 && x >100
```

FAIL - Invalid range.

---

```ts
x > 5 && x < 1000 && x >100
```

```json
{
   x: [{ number: [">", 100, "<", 1000] }]
}
```

---

```ts
(x > 5 || x < 100) && x < 1000
```

```json
{
   x: [{ number: [">", 5, "<", 1000] }, { number: ["<", 100] }]
}
```

When multiple numeric ranges are present, apply the new constraint to them all.

---

```ts
((x > 5 && x < 10) || x < 100) 
```

```json
{
   x: [{ number: [">", 5, "<", 10] }, { number: ["<", 100] }]
}
```

---

```ts
((x > 5 && x < 10) || x < 100) && x > 50 
```

FAIL - The range > 50 cannot be applied to the range 5 < x < 10.

Fail when one of the ranges cannot have the new constraint applied.

**Comment by thantos** [comment]
*Scenario*: Is it possible to have mixed values at a field and how does the `&&` logic work in this case?
*Examples*: 
```ts
b === "x" || b.startsWith("y")
```

```
{
   b: ["x", { prefix: "y" }]
}
```

---

```ts
(b === "x" || b.startsWith("y")) && b === "x"
```

---

```ts
if((b === "x" || !b) && b === "y")
```

FAIL - Cannot AND two matchers on `b`

---

```ts
if((!b || b > 10) && b > 5)
```

```
{
    b: [{ exists: false }, {number: [">", 10, ">", 5]}]
}
```

*Proposal*:
"yes, but"
This shouldn't be a problem, for string/number, prefix, and anything-but say that they fail when not a sub-set and cross-type comparison will never be a subset (for now).
For number range, we will fail if the the other side is not only numeric ranges or `exists: false`.
For `exists:false` always fails on `&&` with anything that isn't an exists: false
For `exists: true`, fail when exists: false exists, otherwise do nothing.

**Comment by thantos** [comment]
### Event Bridge 
Design for how to handle event bus targetting.

* Event targets cannot return, so return type of the function integrations doesn't make sense.
* Event target may have different configuration for each target type
* Not all targets support inputput transformation (bus to bus)
*  

#### Lambda
```ts
bus.
	.when(event => event.source === "dynamo")
	.send(myFunction, event => event.detail)

bus.
	.when(event => event.source === "dynamo")
	.send({
		function: myFunction
		transform: event => event.detail,
		queue: myQueue,
		retry: 10
	})
```

#### Step Functions

```ts
bus
	.when(event => event.source === "dynamo")
	.send(myMachine, event => [event.detail])

bus.
	.when(event => event.source === "dynamo")
	.send({
		machine: myFunction
		transform: event => event.detail,
		queue: myQueue,
		retry: 10,
		role: myRole
	})
```

#### Event Bridge

> Transformation is not allowed when forwarding to event bus

```ts
bus
	.when(event => event.source === "dynamo")
	.send(myOtherBus)
	
bus
	.when(event => event.source === "dynamo")
	.send({ bus: myOtherBus, queue: myQueue, role: myRole }) 
```
#### Dynamo
> Event bridge does not support dynamo as a direct EB target

#### Transforms

What if you have multiple targets with the same format?

```ts
const sub = bus
	.when(event => event.source === "dynamo")
	.as(event => event.detail);

sub.send(myFunction)
sub.send(myMachine)
```

> This will come later
> Not all targets support transformation. For example bus to bus. The send function may need to be different for the `As` and the `When`/Rule objects.
